name: chat
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  badges: ^3.1.2
  bitsdojo_window: ^0.1.6
  dart_openai: ^5.1.0
  envied: ^1.1.0
  flex_color_scheme: ^8.1.0
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.4
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.6+1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  iconfont_convert: ^1.0.2
  envied_generator: ^1.1.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - .env
  fonts:
    - family: IconFont
      fonts:
         - asset: assets/iconfont/iconfont.ttf
