name: chat
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  animated_size_and_fade: ^5.0.3
  awesome_notifications: ^0.10.0
  badges: ^3.1.2
  bitsdojo_window: ^0.1.6
  dart_openai: ^5.1.0
  dropdown_button2: ^2.3.9
  dropdown_search: ^6.0.2
  easy_image_viewer: ^1.5.1
  envied: ^1.1.0
  expandable_menu: ^0.0.5
  ffi: ^2.1.3
  flex_color_scheme: ^8.1.0
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.4
  flutter_highlight: ^0.7.0
  flutter_highlighter: ^0.1.1
  flutter_inappwebview: ^6.1.5
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.6+1
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  ollama_dart: ^0.2.2+1
  popover: ^0.3.1
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  syntax_highlight: ^0.4.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  win32: ^5.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  iconfont_convert: ^1.0.2
  envied_generator: ^1.1.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/images/
    - .env
  fonts:
    - family: IconFont
      fonts:
         - asset: assets/iconfont/iconfont.ttf
