import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

var lightTheme = FlexThemeData.light(
    scheme: FlexScheme.indigoM3,
    scaffoldBackground: Colors.transparent,
    subThemesData: const FlexSubThemesData(
        drawerBackgroundSchemeColor: SchemeColor.transparent,
        interactionEffects: true,
        tintedDisabledControls: true,
        useM2StyleDividerInM3: true,
        inputDecoratorIsFilled: true,
        inputDecoratorBorderType: FlexInputBorderType.outline,
        alignedDropdown: true,
        appBarCenterTitle: false,
        bottomNavigationBarMutedUnselectedLabel: true,
        bottomNavigationBarMutedUnselectedIcon: true,
        navigationBarMutedUnselectedLabel: true,
        navigationBarMutedUnselectedIcon: true,
        navigationBarIndicatorOpacity: 0.03,
        navigationBarIndicatorRadius: 8.0,
        navigationBarBackgroundSchemeColor: SchemeColor.transparent,
        navigationBarHeight: 60.0,
        adaptiveRemoveNavigationBarTint: FlexAdaptive.all(),
        navigationRailUseIndicator: true,
        navigationRailLabelType: NavigationRailLabelType.all,
        cardElevation: 0,
        searchBarElevation: 0.0,
        searchViewElevation: 0.0,
        searchBarRadius: 9.0,
        searchViewRadius: 9.0,
        bottomNavigationBarElevation: 10),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true));
var darkTheme = FlexThemeData.dark(
    scaffoldBackground: Colors.transparent,
    scheme: FlexScheme.indigoM3,
    subThemesData: const FlexSubThemesData(
        drawerBackgroundSchemeColor: SchemeColor.transparent,
        interactionEffects: true,
        tintedDisabledControls: true,
        blendOnColors: true,
        useM2StyleDividerInM3: true,
        inputDecoratorIsFilled: true,
        inputDecoratorBorderType: FlexInputBorderType.outline,
        alignedDropdown: true,
        appBarCenterTitle: false,
        bottomNavigationBarMutedUnselectedLabel: true,
        bottomNavigationBarMutedUnselectedIcon: true,
        navigationBarMutedUnselectedLabel: true,
        navigationBarMutedUnselectedIcon: true,
        navigationBarIndicatorOpacity: 0.03,
        navigationBarIndicatorRadius: 8.0,
        navigationBarBackgroundSchemeColor: SchemeColor.transparent,
        navigationBarHeight: 60.0,
        navigationRailUseIndicator: true,
        navigationRailLabelType: NavigationRailLabelType.all,
        cardElevation: 0,
        searchBarElevation: 0.0,
        searchViewElevation: 0.0,
        searchBarRadius: 9.0,
        searchViewRadius: 9.0,
        bottomNavigationBarElevation: 10),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true));
